"use client";

import { useEffect, useRef, useState } from "react";
import {
  Brain,
  Shield,
  BarChart3,
  Zap,
} from "lucide-react";

interface FeatureHighlight {
  icon: typeof Brain;
  title: string;
  description: string;
  metrics?: { label: string; value: string }[];
  featured?: boolean;
}

const FEATURES: FeatureHighlight[] = [
  {
    icon: Brain,
    title: "AI-Powered Signal Generation",
    description:
      "Every trade signal is generated by Claude with full reasoning output. No black-box indicators — you see the complete analysis chain: market regime, multi-timeframe confluence, and risk assessment before any order is placed.",
    metrics: [
      { label: "Analysis Depth", value: "3 Timeframes" },
      { label: "Reasoning", value: "Full Transparency" },
    ],
    featured: true,
  },
  {
    icon: Zap,
    title: "Real-Time OANDA Integration",
    description:
      "Live order execution through OANDA's REST API with sub-second fill verification. Every position is tracked, reconciled, and monitored in real time.",
  },
  {
    icon: BarChart3,
    title: "Multi-Timeframe Confluence",
    description:
      "H4 trend direction, H1 entry timing, and M15 precision — signals only fire when all three timeframes align. No single-indicator guesswork.",
  },
  {
    icon: Shield,
    title: "Enterprise-Grade Risk Management",
    description:
      "Circuit breakers halt trading on anomalous conditions. Correlation filters prevent overexposure. A two-step kill switch ensures you are always in control.",
  },
];

export default function Testimonials() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.15 }
    );

    observer.observe(container);
    return () => observer.disconnect();
  }, []);

  const featured = FEATURES[0];
  const rest = FEATURES.slice(1);

  return (
    <div ref={containerRef} className="max-w-6xl mx-auto px-6">
      {/* Section header */}
      <div className="mb-12">
        <p
          className="font-mono text-xs uppercase tracking-widest mb-3"
          style={{ color: "#00C896" }}
        >
          Built Different
        </p>
        <h2
          className="font-display text-3xl md:text-4xl font-bold"
          style={{ color: "#FFFFFF" }}
        >
          Why Lumitrade
        </h2>
      </div>

      {/* Grid: featured + sidebar */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Featured highlight */}
        <div
          className="lg:col-span-7 transition-all duration-700"
          style={{
            opacity: isVisible ? 1 : 0,
            filter: isVisible ? "blur(0px)" : "blur(5px)",
            transform: isVisible ? "translateY(0)" : "translateY(20px)",
          }}
        >
          <div
            className="rounded-2xl p-8 h-full border"
            style={{
              backgroundColor: "#0E0F12",
              borderColor: "rgba(255, 255, 255, 0.06)",
              boxShadow:
                "0 4px 24px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.03)",
            }}
          >
            <div className="flex items-center gap-4 mb-6">
              <div
                className="flex items-center justify-center rounded-full"
                style={{
                  width: 56,
                  height: 56,
                  background:
                    "linear-gradient(135deg, rgba(0, 232, 157, 0.15), rgba(61, 142, 255, 0.15))",
                  border: "1px solid rgba(0, 232, 157, 0.2)",
                }}
              >
                <featured.icon size={24} style={{ color: "#00C896" }} />
              </div>
              <div>
                <p
                  className="font-display font-semibold text-lg"
                  style={{ color: "#FFFFFF" }}
                >
                  {featured.title}
                </p>
              </div>
            </div>

            <p
              className="text-lg leading-relaxed mb-8"
              style={{ color: "#A1A1A1" }}
            >
              {featured.description}
            </p>

            {/* Metrics */}
            {featured.metrics && (
              <div
                className="flex gap-6 pt-6"
                style={{
                  borderTop: "1px solid rgba(255, 255, 255, 0.06)",
                }}
              >
                {featured.metrics.map((metric) => (
                  <div key={metric.label}>
                    <p
                      className="font-mono text-xl font-semibold"
                      style={{ color: "#00C896" }}
                    >
                      {metric.value}
                    </p>
                    <p
                      className="text-xs mt-1"
                      style={{ color: "#525252" }}
                    >
                      {metric.label}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Sidebar highlights */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          {rest.map((feature, i) => (
            <div
              key={feature.title}
              className="transition-all duration-700"
              style={{
                opacity: isVisible ? 1 : 0,
                filter: isVisible ? "blur(0px)" : "blur(5px)",
                transform: isVisible ? "translateY(0)" : "translateY(20px)",
                transitionDelay: `${(i + 1) * 150}ms`,
              }}
            >
              <div
                className="rounded-2xl p-6 border transition-all duration-300 hover:-translate-y-0.5"
                style={{
                  backgroundColor: "#0E0F12",
                  borderColor: "rgba(255, 255, 255, 0.06)",
                }}
                onMouseEnter={(e) => {
                  (e.currentTarget as HTMLElement).style.borderColor =
                    "rgba(255, 255, 255, 0.1)";
                  (e.currentTarget as HTMLElement).style.boxShadow =
                    "0 8px 32px rgba(0, 0, 0, 0.3)";
                }}
                onMouseLeave={(e) => {
                  (e.currentTarget as HTMLElement).style.borderColor =
                    "rgba(255, 255, 255, 0.06)";
                  (e.currentTarget as HTMLElement).style.boxShadow = "none";
                }}
              >
                <div className="flex items-center gap-3 mb-3">
                  <div
                    className="flex items-center justify-center rounded-full"
                    style={{
                      width: 40,
                      height: 40,
                      background:
                        "linear-gradient(135deg, rgba(0, 232, 157, 0.1), rgba(61, 142, 255, 0.1))",
                      border: "1px solid rgba(0, 232, 157, 0.15)",
                    }}
                  >
                    <feature.icon size={18} style={{ color: "#00C896" }} />
                  </div>
                  <p
                    className="font-display font-semibold text-sm"
                    style={{ color: "#FFFFFF" }}
                  >
                    {feature.title}
                  </p>
                </div>
                <p
                  className="text-sm leading-relaxed"
                  style={{ color: "#A1A1A1" }}
                >
                  {feature.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
